### ISSUE TITLE
Is this project going to try to update/upgrade Pedalboard2?

### ISSUE THREAD

**Issue by njfsilva** [lrq3000/Pedalboard2#1]
This application is an integral part of my daily life, I'l love to see it maintained/updated/upgraded.

Is this an effort to keep it runnable and vst3 compatible?

**Comment by lrq3000** [comment]
Hello, I am sorry but this is only a mirror, I am not competent enough in vst programming to maintain or further develop this app. I can nevertheless merge others PRs if any is offered.

8 févr. 2024 14:06:30 Nelson Silva ***@***.***>:

**Comment by feathVR** [comment]
I was able to use the vst3 plugin with this application and would like to write about how to use it.

1. use Calra.vst
2. set up vst3 plugin in Calra.vst.

With this method, I was able to use the vst3 plugin in Pedalboard2.

Originally, I thought that since Calra is a vst host plugin, Pedalboard2 did not need to use it, but when I used it as a vst host plugin, the operation was unstable.
When Calra.vst (Calra has a version of the vst plugin) was used with Pedalboard2, the operation was stable and problem-free. In my use case, OSC communication was required, but of course OSC could be used with the vst3 plugin.
https://github.com/falkTX/Carla
